#ifndef IO_MAPPING_STM32F411CE_BLACKPILL_WEACTSTUDIO_V3_0_H_
#define IO_MAPPING_STM32F411CE_BLACKPILL_WEACTSTUDIO_V3_0_H_

/* Pins for leds */
#define BLUE_LED_PIN		(13U)
#define BLUE_LED_PIN_HAL	(GPIO_PIN_13)
#define BLUE_LED_PORT 		(GPIOC)
#define BLUE_LED_BIT 		(1 << BLUE_LED_PIN)

/* Pins for n64 communication */
#define COMMS_N64_STOP_PIN		(5U)
#define COMMS_N64_STOP_PIN_HAL	(GPIO_PIN_5)
#define COMMS_N64_STOP_PORT 	(GPIOB)
#define COMMS_N64_STOP_BIT 		(1 << COMMS_N64_STOP_PIN)
#define COMMS_N64_STOP_SET 		(GPIO_BSRR_BS5)
#define COMMS_N64_STOP_CLEAR 	(GPIO_BSRR_BR5)

#define COMMS_N64_TX_PIN		(6U)
#define COMMS_N64_TX_PIN_HAL	(GPIO_PIN_6)
#define COMMS_N64_TX_PORT 		(GPIOB)
#define COMMS_N64_TX_BIT 		(1 << COMMS_N64_TX_PIN)

#define COMMS_N64_RX_PIN		(7U)
#define COMMS_N64_RX_PIN_HAL	(GPIO_PIN_7)
#define COMMS_N64_RX_PORT 		(GPIOB)
#define COMMS_N64_RX_BIT 		(1 << COMMS_N64_RX_PIN)

#define COMMS_N64_PULLUP_PIN		(8U)
#define COMMS_N64_PULLUP_PIN_HAL	(GPIO_PIN_8)
#define COMMS_N64_PULLUP_PORT 		(GPIOB)
#define COMMS_N64_PULLUP_BIT 		(1 << COMMS_N64_PULLUP_PIN)

#endif
